# Generated by Django 4.1.7 on 2023-02-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='airportstable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('City', models.CharField(blank=True, max_length=200, null=True)),
                ('IATA', models.CharField(blank=True, max_length=200, null=True)),
                ('ICAO', models.CharField(blank=True, max_length=200, null=True)),
                ('Latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('Longitude', models.CharField(blank=True, max_length=200, null=True)),
                ('Altitude', models.CharField(blank=True, max_length=200, null=True)),
                ('Timezone', models.CharField(blank=True, max_length=200, null=True)),
                ('DST', models.CharField(blank=True, max_length=200, null=True)),
                ('Tz', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
