# Generated by Django 4.1.7 on 2023-02-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airportstable',
            old_name='Name',
            new_name='Country',
        ),
    ]
