# Generated by Django 4.1.7 on 2023-02-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0004_rename_pays_airportstable_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airportstable',
            old_name='City',
            new_name='Countrjqsklfy',
        ),
        migrations.RenameField(
            model_name='airportstable',
            old_name='Country',
            new_name='County',
        ),
    ]
