# Generated by Django 4.1.7 on 2023-02-21 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0007_rename_country_airportstable_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airportstable',
            old_name='Countrjqsklfy',
            new_name='Country',
        ),
    ]
