# Generated by Django 4.1.7 on 2023-02-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0008_rename_countrjqsklfy_airportstable_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='finalAirlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Alias', models.CharField(blank=True, max_length=200, null=True)),
                ('IATA', models.CharField(blank=True, max_length=200, null=True)),
                ('ICAO', models.CharField(blank=True, max_length=200, null=True)),
                ('CallSign', models.CharField(blank=True, max_length=200, null=True)),
                ('Country', models.CharField(blank=True, max_length=200, null=True)),
                ('Active', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(blank=True, max_length=200, null=True)),
                ('airlineID', models.CharField(blank=True, max_length=200, null=True)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('sourceID', models.CharField(blank=True, max_length=200, null=True)),
                ('destination', models.CharField(blank=True, max_length=200, null=True)),
                ('destinationID', models.CharField(blank=True, max_length=200, null=True)),
                ('codeshare', models.CharField(blank=True, max_length=200, null=True)),
                ('stops', models.CharField(blank=True, max_length=200, null=True)),
                ('equipment', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
