# Generated by Django 4.1.7 on 2023-02-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0009_finalairlines_routes'),
    ]

    operations = [
        migrations.CreateModel(
            name='retards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Airline', models.CharField(blank=True, max_length=200, null=True)),
                ('Flight', models.CharField(blank=True, max_length=200, null=True)),
                ('AirportFrom', models.CharField(blank=True, max_length=200, null=True)),
                ('AirportTo', models.CharField(blank=True, max_length=200, null=True)),
                ('DayOfWeek', models.CharField(blank=True, max_length=200, null=True)),
                ('Time', models.CharField(blank=True, max_length=200, null=True)),
                ('Length', models.CharField(blank=True, max_length=200, null=True)),
                ('Delay', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
